{
    'name': 'Volan Yasamal',
    'version': '2.6.8',
    'summary': 'Badminton və Basketbol üçün tam idman idarəetmə sistemi',

    'author': 'Aim',
    'website': 'https://github.com/7aim/BadmintonOdoo',
    'category': 'Services/Sport Management',
    'license': 'LGPL-3',
    'images': [
        'static/description/icon.png',
    ],
    'depends': ['base', 'contacts', 'mail', 'hr', 'bus', 'volan_genclikk'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron_jobs.xml',
        'data/badminton_settings.xml',
        'views/res_partner_views.xml',
        'views/sport_system_views.xml',
        'views/badminton_session_filter_views.xml',
        'views/badminton_session_views.xml',
        'views/badminton_sale_views.xml',
        'views/badminton_sale_name_migration_views.xml',
        'views/badminton_package_views.xml',
        'views/badminton_stock_update_wizard_views.xml',
        'views/badminton_product_views.xml',
        'views/badminton_product_sale_views.xml',
        'views/basketball_package_views.xml',
        'views/badminton_lesson_freeze_views.xml',
        'views/badminton_lesson_simple_views.xml',
        'views/badminton_group_views.xml',
        'views/badminton_lesson_payment_views.xml',
        'views/basketball_lesson_freeze_views.xml',
        'views/basketball_lesson_simple_views.xml',
        'views/basketball_group_views.xml',
        'views/basketball_attendance_check_views.xml',
        'views/basketball_demo_lesson_views.xml',
        'views/basketball_lesson_payment_views.xml',
        'views/customer_wizard_views.xml',
        'views/qr_scanner_views.xml',
        'views/session_extend_wizard_views.xml',
        'views/badminton_attendance_check_views.xml',
        'views/menu_views.xml',
        'views/cash_views.xml',
        'reports/basketball_payment_receipt.xml',
        'reports/badminton_payment_receipt.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'volan_yasamal/static/src/css/style.css',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 1,
    'external_dependencies': {
        'python': ['qrcode', 'pillow'],
    },
    'web_icon': 'volan_yasamal/static/description/icon.png'
}
